### ISSUE TITLE
Buttons not registering

### ISSUE THREAD

**Issue by Tigeneer** [minsang-github/arcin-infinitas#13]
While playing Infinitas (new 2020) on this firmware, I've noticed that some buttons will not register at all at random points in time. This was noticable while performing different button chords in rapid succession. Isolating the problem, I stress tested the controller for loose cabling, faulty switches, using a different software to check if the buttons are indeed registering on time, and using a 250hz firmware in the new Infinitas (2020), all of which seem to function properly. Maybe this has something to do with 1000hz polling?

**Comment by kinetic-flow** [comment]
Hm.. try enabling the Debounce option in the conf tool. If that doesn't work I'll consider building a version that run at 250hz.

**Comment by Tigeneer** [comment]
The debounce option does eliminate the buttons-not-registering issue, as well as all of the "POOR" registers on good timing, of which were a separate issue as well. Cool!
  While this is the case, though EXTREMELY nitpicky on my part, it does cause the timing on "GREAT" or higher notes to be very slightly less stable, shifting to a lower tier judge every now and then. (or I could just be playing a bit worse now, it's a mystery to me)

Anyways, debounce works, thanks for the help :)

**Comment by kinetic-flow** [comment]
As of v8, I've added 250hz version of firmware just in case that works better for some people.
