### ISSUE TITLE
Explain sensitivity ratios

### ISSUE THREAD

**Issue by mbilker** [minsang-github/arcin-infinitas#23]
At first glance, I thought the 1:n options increased the sensitivity of connected analogs. After checking the config tool I learned that I was mistaken and that the n:1 options increase the sensitivity. Could a note regarding this be added to the "Configuration tool" section of the README?

**Comment by kinetic-flow** [comment]
Updated README. Yeah, these options came from the original arcin config tool, so I haven't bothered to explain it. Typically people stick to 1:3 or 1:4 when using with Dao. YMMV for custom controllers of course.
