### ISSUE TITLE
Request: Runtime mode switch for Invert QE1

### ISSUE THREAD

**Issue by globalnamespace** [minsang-github/arcin-infinitas#27]
Just a small request to make this switchable via a button combination.

The turntable direction seems to be inverted in \*HID-light applications\* vs infinitas, so when jumping between games it'd be nice to have a quick toggle.

**Comment by lain-2p** [comment]
Dao PCBs used to have a button toggle to switch between X and Y axis input alongside this, I don't know if that should also be a button combination for fear of bloat but I think axis flip would be useful for a number of people.
