### ISSUE TITLE
Unable to start arcin in bootloader mode if WS2812B is plugged in to B9

### ISSUE THREAD

**Issue by lain-2p** [minsang-github/arcin-infinitas#43]
Arcin will seemingly not be able to go in to the bootloader either through software or by holding 1+2 while plugging in if WS2812B is enabled for B9 and the strip is connected, not sure if this is new behaviour for arcins seeing as WS2812B functionality was mostly broken on other firmwares already

on a side note, not something I think deserves its own issue as it feels more like a choice by design, I think it would be good if the LED cap was higher than 60 for niche cases (like my own) where a full Neopixel ring inside the turntable takes up the 60 LED cap leaving no ability to assign colour to any other extraneous LED segments

**Comment by kinetic-flow** [comment]
There is no way to safely update the bootloader via HID, so the first issue won't be fixed. But in the new beta release, I did include new binary (..._upgrade.exe) which will let you boot into the bootloader from the exe.

In the new version I did change the limit from 60 to 180.
